# Generated by Django 6.0.3 on 2026-03-10 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aside', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
    ]
